"""init models, first version

Revision ID: cb4713702040
Revises:
Create Date: 2025-04-10 12:55:21.571703

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb4713702040"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("tables",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("seats", sa.Integer(), nullable=False),
    sa.Column("location", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("reservations",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("customer_name", sa.String(), nullable=False),
    sa.Column("table_id", sa.Integer(), nullable=False),
    sa.Column("reservation_time", sa.DateTime(), nullable=False),
    sa.Column("duration_minutes", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["table_id"], ["tables.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reservations")
    op.drop_table("tables")
    # ### end Alembic commands ###
