name: Validation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_booking_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      CI: ${{ secrets.CI }}
      USE_TEST_DB: ${{ secrets.USE_TEST_DB }}
      GH_POSTGRES_SERVER: ${{ secrets.GH_POSTGRES_SERVER }}
      TEST_POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
      TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
      TEST_POSTGRES_SERVER: ${{ secrets.TEST_POSTGRES_SERVER }}
      TEST_POSTGRES_PORT: ${{ secrets.TEST_POSTGRES_PORT }}
      TEST_POSTGRES_DB: ${{ secrets.TEST_POSTGRES_DB }}
      PYTHONUNBUFFERED: ${{ secrets.PYTHONUNBUFFERED }}
      API_PORT: ${{ secrets.API_PORT }}
      API_VERSION: ${{ secrets.API_VERSION }}
      API_DESCRIPTION: ${{ secrets.API_DESCRIPTION }}
      API_TITLE: ${{ secrets.API_TITLE }}
      PROJECT_VERSION: ${{ secrets.PROJECT_VERSION }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest-asyncio

      - name: Lint with ruff
        run: ruff check

      - name: Run tests with pytest
        run: pytest -v
