name: Validation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_booking_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      CI: "true"
      USE_TEST_DB: "true"
      GH_POSTGRES_SERVER: localhost
      TEST_POSTGRES_USER: postgres
      TEST_POSTGRES_PASSWORD: postgres
      TEST_POSTGRES_SERVER: test_db
      TEST_POSTGRES_PORT: 5432
      TEST_POSTGRES_DB: test_booking_db
      TEST_DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/test_booking_db
      PYTHONUNBUFFERED: 1
      API_PORT: 7000
      API_VERSION: /api/v1
      API_DESCRIPTION: API for booking in restaurant
      API_TITLE: BookingAPI
      PROJECT_VERSION: 1.0.0


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest-asyncio

      - name: Lint with ruff
        run: ruff check

      - name: Run tests with pytest
        run: pytest -v
